version: "3"

services:
  web:
    image: rade363/currency-exchange-widget:latest
    env_file:
      - .env
    ports:
      - "80:5000"
    networks:
      - lan

networks:
  lan:
    driver: bridge
